### ISSUE TITLE
🔧 [Refactor] Use QR-Code Modal Popup on Generate Link

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1867] opened 2022-05-04 16:38 UTC
## 🔧 Refactor ticket

Use QR-Code Modal Popup on Generate Link.
- Make a component out of the modal defined in the TransactionLinkList
- Reuse the component on GenerateLink Page

**Comment by Mogge** [comment] 2022-05-09 14:11
Duplicate of #1826

**Closed by Mogge** 2022-05-09 14:11 UTC
Labels: refactor
