### ISSUE TITLE
🔧 [Refactor] Log Rotation on Server

### ISSUE THREAD

**Issue by Mogge** [gradido/gradido#2197] opened 2022-09-13 12:39 UTC
## 🔧 Refactor ticket

It looks like the log files on the servers are growing very large. Ensure that the log rotation is also triggered for the backend and apollo logs

**Comment by clauspeterhuebner** [comment] 2022-09-20 14:38
duplicate of #2220

**Closed** 2022-09-20 14:41 UTC
Labels: refactor, devops
